project_id = "cgtlmnvwvhktopxavjan"

[functions.ai-scan]
verify_jwt = false

[functions.api-scan]
verify_jwt = false

[functions.multi-scan]
verify_jwt = false

[functions.get-client-ip]
verify_jwt = false
